global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'hrms-api'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
